# render.yaml
services:
  - type: web
    name: warranty-scraper
    runtime: python
    buildCommand: |
      chmod +x build.sh && ./build.sh
    startCommand: streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
    plan: free
