FROM mcr.microsoft.com/devcontainers/python:3.10

RUN apt-get update && apt-get install -y \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libxkbcommon0 \
    libgbm1 \
    libasound2 \
    libnss3 \
    libxss1 \
    libxfixes3 \
    libcairo2 \
    libpango-1.0-0 \
    libgtk-3-0 \
    libgdk-pixbuf2.0-0 \
    libpangocairo-1.0-0 \
    libx11-xcb1 \
    libxcursor1 \
    libcairo-gobject2 \
    libx264-160 \
    libgstreamer1.0-0 \
    libgtk-4-1 \
    libgraphene-1.0-0 \
    libwoff1 \
    libvpx7 \
    libopus0 \
    libflite1 \
    libflite-alsa \
    libflite-dev \
    libharfbuzz-icu0 \
    libavif15 \
    libsecret-1-0 \
    libx264-160 \
    && apt-get clean
